### ISSUE TITLE
when I run the python app.py

### ISSUE THREAD

**Issue by ch0mik** [irl/websdr-plus#1]
ch0mik@MainFrame:~/websdr-plus$ sudo python app.py
Found Rafael Micro R820T tuner
Exact sample rate is: 2000000.052982 Hz
rtlsdr_demod_write_reg failed with -9
r82xx_write: i2c wr failed=-9 reg=06 len=1
Traceback (most recent call last):
  File "app.py", line 52, in <module>
    radio.updateSamples()
  File "app.py", line 25, in updateSamples
    self.samples = self.sdr.read_samples(NUM_SAMPLES_PER_SCAN)
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdr.py", line 328, in read_samples
    raw_data = self.read_bytes(num_bytes)
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdr.py", line 312, in read_bytes
    % (result, num_bytes))
IOError: Error code -8 when reading 32768 bytes
ch0mik@MainFrame:~/websdr-plus$

**Comment by ch0mik** [comment]
PS. on my Cubieboard (ARM) works ok.
- only 144MHz are now, but I will waiting for more ;) !

Vy 73! de SQ7MRU Pawel
